#!/bin/bash


# merge xresources
xrdb -merge ~/.config/X11/Xresources

# add new keyboard layout
setxkbmap us,cz -variant ,qwerty -option grp:alt_shift_toggle

# increase key repeat rate
xset r rate 250 30

# start compositor
picom &

# start xbanish
xbanish &

# set wallpaper
setwall

# start xautolock with slock
xautolock -time 30 -locker i3lock_custom &

# redshift
redshift -l 50:14.5 -t 4500:3500 &

# start wm
while true; do
	dwm 2> ~/.cache/dwm.log
done
